### ISSUE TITLE
Extreme blur with tilt shift effect.

### ISSUE THREAD

**Issue by vukivan** [vukivan/EnhancedZoomContinued#1]

**Comment by tony56a** [comment]
Not sure if this is useful for you, but something [Fr0sZ](https://github.com/Fr0sZ/Skylines-Multiplayer/blob/1cf1d8df13e0bca2b2788bc744100be314683f91/SkylinesMultiplayer/Prefabs/PlayerLocalPrefab.cs) discovered is that DepthOfField can be manipulated after the CameraController has been disabled, so you can disable it/adjust blur focal length/etc. I've been doing something like that with the [First person camera mod](https://github.com/tony56a/Skylines-FPSCamera/blob/d42eca2fe942c9e42fe782a834a7be4213bf26fd/FPSCamera/FPSCamera.cs).

**Comment by vukivan** [comment]
Thanks, that's very useful!
